### ISSUE TITLE
Carrier wave conflict 

### ISSUE THREAD

**Issue by amrdruid** [preston/railroady#100]
When I run rake diagram:all, the following error occurs

/home/amr/bedopedia/doc/models_complete.svg
/home/amr/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/orm/activerecord.rb:9:in `module:ActiveRecord': uninitialized constant CarrierWave::Mount (NameError)

What do you think is happening here ?

**Comment by preston** [comment]
Not sure, but possibly a namespace issue? You might want to search for similar issues, as that sort of thing does happen sometimes for projects with various module namespacing configurations.
