### ISSUE TITLE
Model render issue - missing methods / properties

### ISSUE THREAD

**Issue by BrandtSolovij** [preston/railroady#105]
Hi there, per the title, when generating UML (via either rake or alternative commandline use) the models are recognized but their individual details are omitted - resulting in their contents being empty. 

Project specs :

-Rails 4.2.0
-Ruby 2.2.4
-Graphviz version 2.38.0 (20140413.2041)

thanks

**Comment by psameer1831** [comment]
+Same issue here . fixes ?

**Comment by preston** [comment]
Not sure what the actual issue is, but _usually_ when this happens it's an issue with database connectivity, missing ActiveRecord relationship declarations, and similar.

**Comment by BrandtSolovij** [comment]
This was outside the scope of "normal activerecord use" - specifically: non-db originated models had inherited ActiveRecord for  various convenience reasons but were not truly bound to a DB table(s). Please disregard / the issue is related to my implementation
