### ISSUE TITLE
run rake diagram after each migration (db:migrate)

### ISSUE THREAD

**Issue by tuxtux59** [preston/railroady#125]
Hi,

I'm wondering if some code exists to run ``rake diagram:all`` after each ``rake db:migrate``so that models and controllers are always up to date?

Thanks

**Comment by preston** [comment]
@tuxtux59 `rake` has its own ways of hooking or chaining things together. See: https://stackoverflow.com/questions/1689504/how-do-i-make-a-rake-task-run-after-all-other-tasks-i-e-a-rake-afterbuild-tas
