### ISSUE TITLE
No dependencies specified in gemspec

### ISSUE THREAD

**Issue by lenary** [preston/railroady#42]
This makes it hell to work with. 
Yes, you use plaintext to specify required rails versions, but no more than that, allowing this to be installed in a rails 2.3.x system (which I'm running, and trying to use bundler to find me compatible diagram makers).

**Comment by preston** [comment]
This ticket is quite old, but for anyone looking, the older RailRoad gem is what supported Rails v2. `railroady` has only ever supported v3 onward.
