### ISSUE TITLE
rake -T barking NotImplementedError on Windows 7 (32-bit)

### ISSUE THREAD

**Issue by DHB** [preston/railroady#45]
Sed on windows (GNU or installed along with git) wants option -r for extended Regex.

The railroady.rake task does not check for any other host_os except /linux | cygwin/ 
or /mac | darwin | bsd/. 
Quick workaround was to simply add mingw32.

```ruby
def self.sed
      regex = 's/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g'
      case RbConfig::CONFIG['host_os']
      when /linux|cygwin|mingw32/   # <<< patched 
        return "sed -r '#{regex}'"
      when /mac|darwin|bsd/
        return "sed -E '#{regex}'"
      else
        raise NotImplementedError
      end
    end

```

*Not sure to include other host_os like /mswin|win|mingw/
or even Solaris likewise.* 

*Also dunno when people use MS Visual C to compile gem extensions instead of mingw.*

**Comment by preston** [comment]
Possibly OBE.
