### ISSUE TITLE
Printing large svg diagrams

### ISSUE THREAD

**Issue by IanVaughan** [preston/railroady#48]
Hi, I'm having problems printing the `models_complete.svg` file as it spans many pages.

I'm not sure if its just me (well could be), or if some markup needs to be changed in the svg file?
Here are the size/dimensions parts within the file :

``` xml
<svg width="6137pt" height="3092pt" viewBox="0.00 0.00 6137.00 3092.00">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 3088)">
<polygon fill="white" stroke="white" points="-4,5 -4,-3088 6134,-3088 6134,5 -4,5"/>
```

Which no mater how I try to print it, within either InkScape/Firefox, either comes out very small on one page, or only prints 1 page of it full size!

Any clues/help? Cheers

**Comment by sbrl** [comment]
For those who arrive here and don't want to install Foxit Reader: LibreOffice Draw also does the job.
