### ISSUE TITLE
rake aborted!

### ISSUE THREAD

**Issue by HoplaGeiss** [preston/railroady#92]
I can't run rake diagrame:all
The outpout is: 

```
rake aborted!
Don't know how to build task 'diagram:all'
```

'neato' and 'dot' are available in the commande line..
( I am on ubuntu 14.04, rails 4.2.0 )

**Comment by preston** [comment]
Looks like you have a typo: an 'e' after "diagram". :smile:

**Comment by HoplaGeiss** [comment]
ahha sorry, ( it is diagram in french ), the typo is only in my the issue.
![screenshot from 2015-03-10 20 10 22](https://cloud.githubusercontent.com/assets/5755785/6583017/831a7786-c761-11e4-92ce-105468902f99.png)

**Comment by preston** [comment]
Hmm.. are you sure you have railroady added to your project's Gemfile correctly?

**Comment by HoplaGeiss** [comment]
yeah and I did a bundle install also

**Comment by preston** [comment]
That's the only reason I can think of that would cause this error. Not sure!

**Comment by HoplaGeiss** [comment]
Does the full trace help you ?

![screenshot from 2015-03-10 20 13 52](https://cloud.githubusercontent.com/assets/5755785/6583071/0368d360-c762-11e4-88fa-95b55ab6cd3c.png)

**Comment by preston** [comment]
This looks like the same error you get when there's something wrong with your Gemfile. Try blowing away your Gemfile.lock and re-running `bundle update`.

**Comment by HoplaGeiss** [comment]
ahha, I am ashamed. The gem was in production.
Thanks for taking time to answer such stupid question.

Have a nice day

**Comment by preston** [comment]
No worries. :)
