### ISSUE TITLE
(print:20608): GLib-GObject-WARNING **: The property GtkDialog:has-separator is deprecated and shouldn't be used anymore. It will be removed in a future version.

### ISSUE THREAD

**Issue by synthead** [preston/railroady#96]
This message is displayed on an up-to-date Arch Linux x86_64 system when running `rake diagram:all`:

    (print:20608): GLib-GObject-WARNING **: The property GtkDialog:has-separator is deprecated and shouldn't be used anymore. It will be removed in a future version.

**Comment by preston** [comment]
Hmm .. this is *probably* coming from an underlying dependency such as graphviz. Could you try running the commands manually (as opposed to using the rake tasks) as post the output? Thanks!

**Comment by preston** [comment]
Closing as this seems to have resolved itself.
